version: '2'
services:
  mariadb:
    image: mariadb:10.5
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./persist/mysql:/var/lib/mysql
  php7.0-fpm:
    build: ./php/php7.0-fpm
    restart: always
    user: "www-data:www-data"
    volumes:
      - ./www:/www
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  php7.2-fpm:
    build: ./php/php7.2-fpm
    restart: always
    user: "www-data:www-data"
    volumes:
      - ./www:/www
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  php7.4-fpm:
    build: ./php/php7.4-fpm
    restart: always
    user: "www-data:www-data"
    volumes:
      - ./www:/www
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  php7.4-fpm-xdebug:
    build: ./php/php7.4-fpm-xdebug
    restart: always
    user: "www-data:www-data"
    volumes:
      - ./www:/www
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - /tmp/php7.4-fpm-xdebug/profiler:/tmp/xdebug-output
  php8.1-fpm:
    build: ./php/php8.1-fpm
    restart: always
    user: "www-data:www-data"
    volumes:
      - ./www:/www
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  php8.1-fpm-xdebug:
    build: ./php/php8.1-fpm-xdebug
    restart: always
    user: "www-data:www-data"
    volumes:
      - ./www:/www
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - /tmp/php8.1-fpm-xdebug/profiler:/tmp/xdebug-output
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./www:/www
      - ./nginx/sites:/etc/nginx/sites
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-wp-common.conf:/etc/nginx/nginx-wp-common.conf
      - ./nginx/nginx-php-common.conf:/etc/nginx/nginx-php-common.conf
