version: '2'
services:
  mariadb:
    image: mariadb:10.11
    ports:
      - "127.0.0.1:3366:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./persist/mysql:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./www:/www
      - ./nginx/sites:/etc/nginx/sites
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-wp-common.conf:/etc/nginx/nginx-wp-common.conf
      - ./nginx/nginx-php-common.conf:/etc/nginx/nginx-php-common.conf
